services:
  db:
    image: postgres:18
    container_name: tourplanner-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tourplanner
    ports:
      - "${DB_PORT:-5432}:5432"