spring.application.name=backend
springdoc.swagger-ui.path=/docs

#JPA
spring.datasource.url=jdbc:postgresql://localhost:5432/tourplanner
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update