spring.application.name=backend
springdoc.swagger-ui.path=/docs
spring.profiles.active=local

#JPA
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT:5432}/tourplanner
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.at.technikum.backend=debug

jwt.secret=5367566859703373367639792F423F452848284D6251655468576D5A71347437