spring.application.name=backend
springdoc.swagger-ui.path=/docs

# H2 Database Connection
spring.datasource.url=jdbc:h2:mem:tourplanner
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=

# JPA/Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.show-sql=true